image: Ubuntu1804 #образ для сборки
stack: node 12    #окружение (версия Node.js)
branches: 
  only:
    - master  #ветка git, откуда берем информацию для сборки
cache: node_modules #кэширование (откуда будут браться кэшированные пакеты)
install:
  - npm install # команда установки зависимостей
build: off      # указание, что не используется сборка (не используем Web-pack)
test_script:
  - npm run lint && npm test  #скрипт сборки (две команды друг за другом запускаются)